### ISSUE TITLE
It was too hard to install

### ISSUE THREAD

**Issue by ghost** [573dev/gfdm-server#3]
Can you have more guideline for it? for Windows version.

**Comment by 573dev** [comment]
Hi. Thanks for the issue. I don't do dev on python on windows so I'm not sure what the instructions would be. If someone that uses windows gets this setup I'd be happy to accept a pull request that explains the setup a bit more.

**Comment by ghost** [comment]
Hi , do you have detail guideline in Centos 7? i have try multiple times and stuck in pip install venv venv
the guideline are too less

**Comment by 573dev** [comment]
I know this is insanely old but I'm just not working on this anymore so I'm going to close this.
